const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={token:localStorage.getItem('lamf.token')||'',records:[],filter:'all',status:null};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const label=s=>String(s||'memory').replaceAll('_',' ');
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)};
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Authorization':`Bearer ${state.token}`,'Content-Type':'application/json',...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(r.status===401){openAuth();throw new Error('Please unlock LAMF')};if(!r.ok)throw new Error(data.error?.message||'LAMF could not complete that');return data}
function openAuth(){$('#auth-error').hidden=true;$('#auth-dialog').showModal();setTimeout(()=>$('#token-input').focus(),80)}
function dateLabel(){const d=new Date();$('#today-label').textContent=d.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});const h=d.getHours();$('#daypart').textContent=h<12?'morning':h<18?'afternoon':'evening'}
function ago(seq){return seq?`Updated at memory ${seq}`:'Kept locally'}
function card(r){return `<button class="memory-card" data-record="${esc(r.id)}"><span class="type">${esc(label(r.type))}</span><h3>${esc(r.title)}</h3><p>${esc(r.body)}</p><span class="card-foot"><span>${esc(r.scope)}</span><span>v${esc(r.version)}</span></span></button>`}
function row(r){return `<button class="library-row" data-record="${esc(r.id)}"><span class="type">${esc(label(r.type))}</span><span><h3>${esc(r.title)}</h3><p>${esc(r.body).slice(0,240)}</p></span><span class="meta">${esc(ago(r.updated_seq))}</span></button>`}
function render(){const recent=state.records.slice(0,6);$('#recent-grid').innerHTML=recent.length?recent.map(card).join(''):'<div class="empty-card">Your library is quiet. Remember your first useful thing.</div>';const shown=state.filter==='all'?state.records:state.records.filter(r=>r.type===state.filter);$('#library-list').innerHTML=shown.length?shown.map(row).join(''):'<div class="empty-card">No memories of this kind yet.</div>';bindRecords()}
function bindRecords(){$$('[data-record]').forEach(b=>b.onclick=()=>openRecord(b.dataset.record))}
async function load(){const [records,status,approvals]=await Promise.all([api('/v1/records?limit=100'),api('/v1/status'),api('/v1/approvals')]);state.records=records.records||[];state.status=status;render();renderStatus(status);renderApprovals(approvals.pending||[])}
function renderStatus(s){const healthy=(s.spool||0)===0&&(s.quarantined||0)===0;$('#health-label').textContent=healthy?'Your memory is in good shape':'Your memory needs a little attention';$('#health-copy').textContent=`${s.records||0} memories · ${s.events||0} trusted events · profile: ${label(s.profile)}`;$('#health-details').innerHTML=[['Memories',s.records||0],['Trusted events',s.events||0],['Waiting to file',s.spool||0],['Needs review',s.pending_approvals||0]].map(([k,v])=>`<div class="health-stat"><strong>${esc(v)}</strong><span>${esc(k)}</span></div>`).join('')}
function renderApprovals(items){const c=$('#review-count');c.hidden=!items.length;c.textContent=items.length;$('#review-list').innerHTML=items.length?items.map(a=>`<article class="library-row"><span class="type">Review</span><span><h3>${esc(a.action||a.id)}</h3><p>${esc(a.reason||a.subject||'LAMF is asking for your decision.')}</p></span><span><button class="filter" data-approval="${esc(a.id)}" data-action="deny">Not now</button> <button class="primary-button" data-approval="${esc(a.id)}" data-action="approve">Approve</button></span></article>`).join(''):'<div class="empty-card">Nothing is waiting for you. You’re all caught up.</div>';$$('[data-approval]').forEach(b=>b.onclick=()=>decide(b.dataset.approval,b.dataset.action))}
async function decide(id,action){await api(`/v1/approvals/${encodeURIComponent(id)}`,{method:'POST',body:JSON.stringify({action,reason:'Decided in standalone LAMF'})});toast(action==='approve'?'Approved':'Declined');await load()}
async function openRecord(id){try{const {record:r}=await api(`/v1/records/${encodeURIComponent(id)}?include_history=true`);$('#record-content').innerHTML=`<div class="record-sheet"><button class="close-button corner" data-close="record-dialog">×</button><p class="eyebrow">${esc(label(r.type))}</p><h2 id="record-title">${esc(r.title)}</h2><div class="record-meta"><span class="tag">${esc(r.scope)}</span><span class="tag">Version ${esc(r.version)}</span><span class="tag">${esc(label(r.confidence))} confidence</span></div><div class="record-body">${esc(r.body)}</div><p>${r.superseded_chain?.length?`This memory builds on ${r.superseded_chain.length} earlier version${r.superseded_chain.length===1?'':'s'}.`:'This is the current version.'}</p></div>`;bindCloses();$('#record-dialog').showModal()}catch(e){toast(e.message)}}
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}-view`));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===name));scrollTo({top:0,behavior:'smooth'})}
function openSearch(){$('#search-dialog').showModal();setTimeout(()=>$('#search-input').focus(),80)}
let timer;async function search(q){if(!q.trim()){return}$('#search-results').innerHTML='<div class="empty-card loading">Looking through your memory…</div>';try{const d=await api(`/v1/search?q=${encodeURIComponent(q)}&limit=20`);$('#search-results').innerHTML=d.results.length?d.results.map(r=>`<button class="search-result" data-record="${esc(r.record_id)}"><small>${esc(label(r.scope))}</small><h3>${esc(r.title)}</h3><p>${esc(r.snippet)}</p></button>`).join(''):'<div class="empty-card">Nothing matched that yet. Try a broader phrase.</div>';bindRecords()}catch(e){toast(e.message)}}
function bindCloses(){$$('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close())}
$('#auth-form').onsubmit=async e=>{e.preventDefault();state.token=$('#token-input').value.trim();try{await api('/v1/health');localStorage.setItem('lamf.token',state.token);$('#auth-dialog').close();await load();toast('Welcome back')}catch(err){$('#auth-error').hidden=false;$('#auth-error').textContent='That key did not open this memory.'}};
$('#remember-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/v1/records',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});e.currentTarget.reset();e.currentTarget.scope.value='project:brain';$('#remember-dialog').close();await load();toast('Memory kept')}catch(err){$('#remember-error').hidden=false;$('#remember-error').textContent=err.message}};
$('#search-input').oninput=e=>{clearTimeout(timer);timer=setTimeout(()=>search(e.target.value),260)};$$('[data-query]').forEach(b=>b.onclick=()=>{$('#search-input').value=b.dataset.query;search(b.dataset.query)});$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;render()});$('#search-open').onclick=$('#hero-search').onclick=openSearch;$('#remember-open').onclick=()=>$('#remember-dialog').showModal();$('#health-open').onclick=()=>$('#health-dialog').showModal();document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape')$$('dialog[open]').forEach(d=>d.close())});$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));bindCloses();dateLabel();if(state.token)load().catch(()=>{});else openAuth();
