"""GUI installer + one-file EXE packaging tests.

Focus: the guarantees a PyInstaller one-file build can silently break.

  1. resource discovery works frozen and unfrozen;
  2. the payload staged out of the bundle is complete and excludes machine
     state (.venv, __pycache__, *.pyc);
  3. the GUI's choices map to a command line install.py actually accepts;
  4. END TO END: after staging out of a simulated ``_MEIxxxx`` directory, the
     launchers and harness registrations generated by the installer core point
     at the PERMANENT installation directory and contain no temp path.

No Tk main loop is started, so this runs headless in CI.
"""

from __future__ import annotations

import ast
import contextlib
import importlib.util
import io
import json
import os
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GUI_PATH = ROOT / "installer" / "windows_gui.py"
SPEC_PATH = ROOT / "installer" / "LAMF.spec"
BUILD_SCRIPT = ROOT / "installer" / "Build-LAMF-Exe.ps1"

_spec = importlib.util.spec_from_file_location("lamf_windows_gui", GUI_PATH)
gui = importlib.util.module_from_spec(_spec)
assert _spec and _spec.loader
# Register before exec: @dataclass resolves its own module via sys.modules.
sys.modules["lamf_windows_gui"] = gui
_spec.loader.exec_module(gui)


def quiet(fn, *args, **kwargs):
    """Run a chatty installer-core function without flooding the test output."""
    buffer = io.StringIO()
    with contextlib.redirect_stdout(buffer):
        return fn(*args, **kwargs)


def spec_constants() -> dict:
    """Module-level literals from LAMF.spec, read without executing PyInstaller."""
    tree = ast.parse(SPEC_PATH.read_text(encoding="utf-8"))
    out: dict = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if not isinstance(target, ast.Name):
            continue
        try:
            out[target.id] = ast.literal_eval(node.value)
        except ValueError:
            continue
    return out


def make_fake_payload(root: Path) -> Path:
    """A miniature package tree that carries the exclusions we care about."""
    (root / "installer").mkdir(parents=True)
    (root / "installer" / "install.py").write_text("# install\n", encoding="utf-8")
    (root / "installer" / "__pycache__").mkdir()
    (root / "installer" / "__pycache__" / "install.cpython-312.pyc").write_bytes(b"\x00")
    (root / "runtime" / "lamf").mkdir(parents=True)
    (root / "runtime" / "lamf" / "cli.py").write_text("# cli\n", encoding="utf-8")
    (root / "runtime" / "lamf" / "stale.pyc").write_bytes(b"\x00")
    (root / "runtime" / "requirements.txt").write_text("pyyaml\n", encoding="utf-8")
    (root / "runtime" / ".venv" / "Scripts").mkdir(parents=True)
    (root / "runtime" / ".venv" / "Scripts" / "python.exe").write_bytes(b"MZ")
    (root / "05_INTEGRATIONS").mkdir()
    (root / "05_INTEGRATIONS" / "README.md").write_text("x\n", encoding="utf-8")
    (root / "VERSION").write_text("2.0.0\n", encoding="utf-8")
    return root


# ---------------------------------------------------------------------------
def test_resource_discovery() -> None:
    root = gui.payload_root()
    assert root == ROOT, f"unfrozen payload root should be the package: {root}"
    assert (root / "installer" / "install.py").is_file()
    assert gui.is_frozen() is False
    assert gui.package_version(root) == (ROOT / "VERSION").read_text(encoding="utf-8").strip()

    # Frozen discovery reads _MEIPASS/payload and never the EXE's own folder.
    with tempfile.TemporaryDirectory() as td:
        fake_mei = Path(td) / "_MEI123456"
        (fake_mei / gui.PAYLOAD_DIR_NAME).mkdir(parents=True)
        sys.frozen = True  # type: ignore[attr-defined]
        sys._MEIPASS = str(fake_mei)  # type: ignore[attr-defined]
        try:
            assert gui.is_frozen() is True
            assert gui.payload_root() == fake_mei / gui.PAYLOAD_DIR_NAME
            needles = gui.temp_needles()
            assert "_MEI" in needles and str(fake_mei) in needles
        finally:
            del sys.frozen  # type: ignore[attr-defined]
            del sys._MEIPASS  # type: ignore[attr-defined]
    assert gui.is_frozen() is False
    print("PASS resource discovery: frozen (_MEIPASS/payload) and source layouts")


def test_installer_core_is_reused() -> None:
    core = gui.load_installer_core()
    # The GUI must not carry its own copy of the harness or profile lists.
    assert core.HARNESSES and core.PROFILES
    catalog = gui.harness_catalog()
    ids = tuple(c.id for c in catalog)
    assert ids == tuple(core.HARNESSES), f"{ids} != {core.HARNESSES}"
    assert all(c.label for c in catalog)

    # Every harness the runtime registry knows must be selectable in the GUI,
    # so an expansion of the registry can never silently drop out of the UI.
    registry = gui._import_runtime_harness()
    assert registry is not None, "bundled runtime lamf.harness must be importable"
    assert set(registry.HARNESSES) == set(ids), (
        f"runtime registry {sorted(registry.HARNESSES)} != GUI {sorted(ids)}")
    hints = {c.id: c.config_hint for c in catalog}
    assert hints["kimi"] == registry.HARNESSES["kimi"].config_path
    assert all(name in dict(gui.profile_catalog()) for name in core.PROFILES)
    print(f"PASS installer core reuse: {len(ids)} harnesses, "
          f"{len(core.PROFILES)} profiles, single source of truth")


def test_payload_contract_matches_spec() -> None:
    consts = spec_constants()
    assert tuple(consts["PAYLOAD_ITEMS"]) == tuple(gui.PAYLOAD_ITEMS)
    assert consts["PAYLOAD_DIR_NAME"] == gui.PAYLOAD_DIR_NAME
    assert set(consts["EXCLUDE_DIRS"]) == set(gui.STAGE_EXCLUDE_DIRS)
    assert set(consts["EXCLUDE_SUFFIXES"]) == set(gui.STAGE_EXCLUDE_SUFFIXES)

    spec_text = SPEC_PATH.read_text(encoding="utf-8")
    assert "console=False" in spec_text, "the EXE must not open a console window"
    assert 'name="LAMF"' in spec_text, "the build must produce LAMF.exe"
    assert "runtime_tmpdir=None" in spec_text
    assert "windows_gui.py" in spec_text
    assert BUILD_SCRIPT.is_file()
    build_text = BUILD_SCRIPT.read_text(encoding="utf-8")
    assert "LAMF.spec" in build_text and "installer_gui_test.py" in build_text
    # Every child process the GUI starts must be windowless too.
    gui_text = GUI_PATH.read_text(encoding="utf-8")
    assert gui_text.count("creationflags=CREATE_NO_WINDOW") >= 3
    assert "CREATE_NO_WINDOW = 0x08000000" in gui_text
    print("PASS packaging contract: spec, build script and GUI agree; no console")


def test_staging_excludes_machine_state() -> None:
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        source = make_fake_payload(root / "src")
        dest = root / "install"
        staged = gui.stage_payload(dest, source)
        assert staged == dest.resolve()
        assert (staged / "installer" / "install.py").is_file()
        assert (staged / "runtime" / "lamf" / "cli.py").is_file()
        assert (staged / "VERSION").is_file()
        assert not (staged / "runtime" / ".venv").exists(), "venv must not be staged"
        assert not (staged / "installer" / "__pycache__").exists()
        assert not (staged / "runtime" / "lamf" / "stale.pyc").exists()

        # A venv already built at the destination survives an upgrade re-stage.
        marker = staged / "runtime" / ".venv" / "keep.txt"
        marker.parent.mkdir(parents=True)
        marker.write_text("existing venv\n", encoding="utf-8")
        gui.stage_payload(dest, source)
        assert marker.is_file(), "re-staging must not delete an existing venv"

        # Installing in place (source checkout) is a no-op, not a self-copy.
        assert gui.stage_payload(source, source) == source.resolve()

        # An incomplete bundle fails loudly instead of installing something broken.
        broken = root / "broken"
        (broken / "VERSION").parent.mkdir(parents=True)
        (broken / "VERSION").write_text("0\n", encoding="utf-8")
        try:
            gui.stage_payload(root / "out2", broken)
        except RuntimeError as exc:
            assert "missing" in str(exc) or "nothing to install" in str(exc)
        else:  # pragma: no cover
            raise AssertionError("incomplete payload must raise")
    print("PASS staging: complete payload, no .venv/__pycache__/*.pyc, idempotent")


def test_install_argv_is_accepted_by_install_py() -> None:
    core = gui.load_installer_core()
    data = Path(tempfile.gettempdir()) / "lamf-argv-data"
    install_dir = Path(tempfile.gettempdir()) / "lamf-argv-app"
    vault = Path(tempfile.gettempdir()) / "lamf-argv-vault"

    opts = gui.InstallOptions(
        data_dir=data, install_dir=install_dir, profile="locked",
        harnesses=("codex", "kimi", "openclaw"), obsidian=True, vault=vault,
        git_vault=True, start_server=False, allow_git_data_dir=True)
    argv = gui.build_install_argv("py.exe", install_dir / "installer" / "install.py", opts)
    parsed = core.parse_args(argv[2:])
    assert parsed.data_dir == str(data)
    assert parsed.profile == "locked"
    assert parsed.harness == ["codex", "kimi", "openclaw"]
    assert parsed.obsidian == "parallel" and parsed.vault == str(vault)
    assert parsed.git_mode == "vault"
    assert parsed.no_start is True and parsed.allow_git_data_dir is True
    # Multi-select is independent: the parsed list resolves back to the same set.
    assert core.choose_harnesses(parsed.harness, interactive=False) == opts.harnesses

    # Every harness at once, and none at all, are both first-class.
    every = tuple(core.HARNESSES)
    argv_all = gui.build_install_argv("py.exe", "i.py", gui.InstallOptions(
        data_dir=data, install_dir=install_dir, harnesses=every))
    assert core.choose_harnesses(core.parse_args(argv_all[2:]).harness,
                                 interactive=False) == every

    bare = gui.InstallOptions(data_dir=data, install_dir=install_dir)
    argv_none = gui.build_install_argv("py.exe", "i.py", bare)
    parsed_none = core.parse_args(argv_none[2:])
    assert parsed_none.harness == ["none"]
    assert core.choose_harnesses(parsed_none.harness, interactive=False) == ()
    assert parsed_none.obsidian == "none" and parsed_none.vault is None
    assert parsed_none.git_mode == "none" and parsed_none.no_start is False
    assert parsed_none.allow_git_data_dir is False
    assert parsed_none.profile == core.DEFAULT_PROFILE
    print("PASS option mapping: none / multi-select / all harnesses accepted by install.py")


def test_python_discovery() -> None:
    info = gui.probe_python([sys.executable])
    assert info is not None and info.version >= (3, 10)
    assert Path(info.path).is_file()
    assert gui.probe_python([str(Path(tempfile.gettempdir()) / "no-such-python")]) is None
    found = gui.find_system_python()
    assert found is not None and found.version >= gui.MIN_PYTHON, (
        "a 3.10+ interpreter is required to run these tests")
    print(f"PASS interpreter discovery: {found.label}")


def test_temp_path_scanner() -> None:
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        clean = root / "clean.ps1"
        clean.write_text(r"$Runtime = 'C:\Program Files\LAMF\runtime'", encoding="utf-8")
        dirty = root / "dirty.json"
        dirty.write_text(json.dumps(
            {"command": r"C:\Users\x\AppData\Local\Temp\_MEI123456\payload\runtime\p.exe"}),
            encoding="utf-8")
        hits = gui.scan_for_temp_paths([clean, dirty, root / "absent.txt"])
        assert [p.name for p, _ in hits] == ["dirty.json"]
        assert hits[0][1] == "_MEI"
        assert gui.scan_for_temp_paths([clean]) == []
    print("PASS temp-path scanner: _MEIPASS references are detected, clean files pass")


def test_end_to_end_permanent_paths() -> None:
    """The core guarantee: nothing generated points into the unpack directory."""
    core = gui.load_installer_core()
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        # 1. Simulate the one-file bundle unpacking into a temp _MEI folder.
        mei = root / "_MEI778899"
        bundle = gui.stage_payload(mei / gui.PAYLOAD_DIR_NAME, ROOT)
        assert (bundle / "installer" / "install.py").is_file()

        # 2. Stage out of it to a permanent installation directory.
        install_dir = root / "Programs" / "LAMF"
        staged = gui.stage_payload(install_dir, bundle)

        # 3. The staged installer core resolves its own permanent paths.
        staged_core = gui.load_installer_core(staged)
        assert staged_core.package_root() == staged
        assert staged_core.runtime_dir() == staged / "runtime"

        # 4. Generate exactly what a real install writes: launchers + adapters.
        data_dir = root / "LAMF-Data"
        os.environ["LAMF_DATA_DIR"] = str(data_dir)
        ui = staged_core.UI()
        quiet(staged_core.write_helper_scripts, ui, data_dir, data_dir / "vault")
        quiet(staged_core.write_harness_registrations, ui, data_dir,
              tuple(staged_core.HARNESSES))

        artifacts = gui.installed_artifacts(data_dir, ())
        names = {p.name for p in artifacts}
        assert {"start-lamf.ps1", "stop-lamf.ps1", "selection.json"} <= names
        assert any(n.startswith("kimi.") for n in names), names

        # 5. No artifact may reference the unpack directory.
        needles = ["_MEI", str(mei), str(bundle)]
        leaks = gui.scan_for_temp_paths(artifacts, needles)
        assert not leaks, f"temp paths leaked into: {[str(p) for p, _ in leaks]}"

        report = gui.verify_permanent_paths(data_dir, staged, (), needles=needles)
        assert report.leaks == []
        assert report.anchored, f"{report.anchor_file} is not anchored to {staged}"
        assert not report.unanchored, [str(p) for p in report.unanchored]
        assert report.ok

        # 6. Positively: launchers and MCP registrations name the install dir.
        #    JSON/TOML registrations escape backslashes, so match every spelling.
        launcher = (data_dir / "bin" / "start-lamf.ps1").read_text(encoding="utf-8")
        assert str(staged / "runtime") in launcher
        assert str(staged / "runtime" / ".venv") in launcher
        for name in ("codex.toml", "claude.json", "hermes.yaml"):
            text = (data_dir / "adapters" / name).read_text(encoding="utf-8")
            assert any(v in text for v in gui.path_variants(staged / "runtime")), name
        selection = json.loads(
            (data_dir / "adapters" / "selection.json").read_text(encoding="utf-8"))
        assert selection["harnesses"] == list(staged_core.HARNESSES)
        assert selection["shared_data_dir"] == str(data_dir)

        # 7. A regression check with the scanner pointed at a poisoned file.
        poisoned = data_dir / "bin" / "poisoned.ps1"
        poisoned.write_text(f"$Runtime = '{bundle}'\n", encoding="utf-8")
        bad = gui.verify_permanent_paths(data_dir, staged, (), needles=needles)
        assert bad.leaks and not bad.ok, "the scanner must catch a poisoned launcher"
        poisoned.unlink()
    os.environ.pop("LAMF_DATA_DIR", None)
    print("PASS end-to-end: launchers and harness configs are anchored to the "
          "permanent install, never to _MEIPASS")


def test_install_record_round_trip() -> None:
    with tempfile.TemporaryDirectory() as td:
        install_dir = Path(td) / "app"
        install_dir.mkdir()
        opts = gui.InstallOptions(
            data_dir=Path(td) / "data", install_dir=install_dir, profile="trusted-local",
            harnesses=("claude", "gemini"), obsidian=True, vault=Path(td) / "vault")
        path = gui.write_install_record(install_dir, opts,
                                        gui.PythonInfo(sys.executable, (3, 12)))
        assert path.name == gui.INSTALL_RECORD
        record = gui.read_install_record(install_dir)
        assert record["profile"] == "trusted-local"
        assert record["harnesses"] == ["claude", "gemini"]
        assert record["data_dir"] == str(Path(td) / "data")
        assert record["vault"] == str(Path(td) / "vault")
        assert gui.read_install_record(Path(td) / "nothing-here") == {}
    print("PASS install record: choices persist for the next run")


def test_path_helpers() -> None:
    home = Path.home()
    assert gui.expand_path("~") == home.resolve()
    assert gui.expand_path('  "~"  ') == home.resolve()
    assert gui.is_within(home / "a" / "b", home) is True
    assert gui.is_within(home, home / "a") is False
    # Program files and memory data must be separable directories.
    assert gui.default_data_dir() != gui.default_install_dir()
    print("PASS path helpers: expansion, containment, distinct defaults")


TESTS = (
    test_resource_discovery,
    test_installer_core_is_reused,
    test_payload_contract_matches_spec,
    test_staging_excludes_machine_state,
    test_install_argv_is_accepted_by_install_py,
    test_python_discovery,
    test_temp_path_scanner,
    test_end_to_end_permanent_paths,
    test_install_record_round_trip,
    test_path_helpers,
)


def main() -> int:
    failures = 0
    for test in TESTS:
        try:
            test()
        except AssertionError as exc:
            failures += 1
            print(f"FAIL {test.__name__}: {exc}")
        except Exception as exc:  # noqa: BLE001
            failures += 1
            print(f"ERROR {test.__name__}: {type(exc).__name__}: {exc}")
    print()
    if failures:
        print(f"{failures} of {len(TESTS)} GUI installer tests failed")
        return 1
    print(f"{len(TESTS)} GUI installer tests passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
