// LAMF Windows launcher
//
// A tiny Rust program with no external dependencies.  The executable's base
// name decides its behavior:
//
//   lamf.exe         -> exec <exedir>\python\pythonw.exe -m lamf.cli <args>
//   lamf-control.exe -> exec <exedir>\python\pythonw.exe -m lamf.cli serve --data-dir <data_dir>
//   uninstall.exe    -> exec <exedir>\python\pythonw.exe -m installer.windows.uninstall_helper /APP_DIR=<app> /DATA_DIR=<data_dir> <args>
//                       with PYTHONPATH=<exedir>\app so package-relative imports resolve
//
// The launcher reads install-state.json from the directory containing the
// executable, sets LAMF_DATA_DIR from the "data_dir" field, and never places
// secrets on the command line.
//
// On non-Windows platforms this source compiles to a stub that prints an error.

use std::process::exit;

#[cfg(windows)]
use std::{env, path::PathBuf, process::{Command, Stdio}};


#[cfg(not(windows))]
fn main() {
    eprintln!("error: LAMF launcher is Windows-only");
    exit(1);
}


/// Parse a four-digit JSON `\uXXXX` escape into a Unicode scalar value.
/// Handles UTF-16 surrogate pairs and returns `None` for invalid escapes.
fn parse_json_hex_escape(iter: &mut std::str::Chars) -> Option<char> {
    let mut value: u32 = 0;
    for _ in 0..4 {
        let c = iter.next()?;
        value = (value << 4) | c.to_digit(16)? as u32;
    }

    // High surrogate: expect a following low surrogate.
    if (0xD800..=0xDBFF).contains(&value) {
        if iter.next() != Some('\\') {
            return None;
        }
        if iter.next() != Some('u') {
            return None;
        }
        let mut low: u32 = 0;
        for _ in 0..4 {
            let c = iter.next()?;
            low = (low << 4) | c.to_digit(16)? as u32;
        }
        if !(0xDC00..=0xDFFF).contains(&low) {
            return None;
        }
        let scalar = 0x10000 + ((value - 0xD800) << 10) | (low - 0xDC00);
        return char::from_u32(scalar);
    }

    char::from_u32(value)
}

/// Extract a JSON string field value with full JSON string unescaping.
/// Only used for the install-state.json generated by the installer, so a
/// tiny hand-rolled parser avoids pulling in any dependencies.
fn json_string_field(text: &str, key: &str) -> Option<String> {
    let search = format!("\"{}\"", key);
    let start = text.find(&search)?;
    let rest = &text[start + search.len()..];

    // Skip whitespace up to ':'.
    let mut iter = rest.char_indices();
    let after_colon = loop {
        match iter.next() {
            Some((_, c)) if c.is_whitespace() => continue,
            Some((i, ':')) => break &rest[i + 1..],
            _ => return None,
        }
    };

    // Skip whitespace up to opening quote.
    let after = after_colon.trim_start();
    if !after.starts_with('"') {
        return None;
    }

    let mut value = String::new();
    let mut iter = after[1..].chars();
    while let Some(c) = iter.next() {
        if c == '\\' {
            match iter.next() {
                Some('"') => value.push('"'),
                Some('\\') => value.push('\\'),
                Some('/') => value.push('/'),
                Some('b') => value.push('\u{0008}'),
                Some('f') => value.push('\u{000C}'),
                Some('n') => value.push('\n'),
                Some('r') => value.push('\r'),
                Some('t') => value.push('\t'),
                Some('u') => value.push(parse_json_hex_escape(&mut iter)?),
                _ => return None,
            }
        } else if c == '"' {
            return Some(value);
        } else {
            value.push(c);
        }
    }
    None
}


#[cfg(windows)]
fn fail(msg: &str) -> ! {
    eprintln!("error: {}", msg);
    exit(1);
}


#[cfg(windows)]
fn configure_uninstall_stdio(cmd: &mut Command) {
    // When Inno Setup launches uninstall.exe with SW_HIDE, the inherited
    // stdout/stderr handles are invalid.  CPython startup crashes if it tries
    // to write to them before uninstall_helper.main can redirect to /LOG_FILE.
    // Point all three stdio streams at the null device for the uninstall branch
    // only; lamf.exe and lamf-control.exe keep inherited handles so console
    // output and agent stdio still work.
    cmd.stdin(Stdio::null());
    cmd.stdout(Stdio::null());
    cmd.stderr(Stdio::null());
}


#[cfg(windows)]
fn main() {
    let exe_path = env::current_exe().unwrap_or_else(|e| fail(&format!("cannot determine executable path: {}", e)));
    let exe_dir = exe_path.parent().map(PathBuf::from).unwrap_or_else(|| fail("cannot determine executable directory"));
    let base = exe_path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("")
        .to_lowercase();

    let state_path = exe_dir.join("install-state.json");
    let state_text = std::fs::read_to_string(&state_path)
        .unwrap_or_else(|e| fail(&format!("cannot read {}: {}", state_path.display(), e)));

    let data_dir = json_string_field(&state_text, "data_dir")
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| fail("data_dir missing from install-state.json"));

    let python = exe_dir.join("python").join("pythonw.exe");
    if !python.exists() {
        fail(&format!("runtime not found: {}", python.display()));
    }

    let mut cmd = Command::new(&python);

    // Force UTF-8 mode for the embedded Python interpreter so Unicode install
    // and data paths work on Windows even when the legacy ANSI code page is
    // active.  Command inherits the parent environment by default, so PATH,
    // HOME, and installer variables remain available.
    cmd.env("PYTHONUTF8", "1");
    cmd.env("PYTHONIOENCODING", "utf-8");

    if base == "uninstall" {
        // The uninstall helper is a package module; run it with -m so relative
        // imports inside installer/windows resolve.  PYTHONPATH points at the
        // packaged app directory, and the explicit app/data switches let the
        // helper locate install-state.json without relying on cwd.
        let app_dir = exe_dir.clone();
        let app_pkg = app_dir.join("app");
        if !app_pkg.is_dir() {
            fail(&format!("app package not found: {}", app_pkg.display()));
        }
        let pythonpath = match env::var("PYTHONPATH") {
            Ok(existing) if !existing.is_empty() => format!("{};{}", app_pkg.display(), existing),
            _ => app_pkg.display().to_string(),
        };
        cmd.env("PYTHONPATH", pythonpath);
        cmd.arg("-m").arg("installer.windows.uninstall_helper");
        cmd.arg("/APP_DIR").arg(&app_dir);
        cmd.arg("/DATA_DIR").arg(&data_dir);
        configure_uninstall_stdio(&mut cmd);
    } else {
        cmd.arg("-m").arg("lamf.cli");
        cmd.env("LAMF_DATA_DIR", &data_dir);

        if base == "lamf-control" {
            cmd.arg("serve").arg("--data-dir").arg(&data_dir);
        }
    }

    // Append any arguments passed to the launcher, skipping the program name.
    for arg in env::args().skip(1) {
        cmd.arg(arg);
    }

    let status = cmd.status()
        .unwrap_or_else(|e| fail(&format!("failed to launch {}: {}", python.display(), e)));

    exit(status.code().unwrap_or(1));
}


#[cfg(test)]
mod tests {
    use super::json_string_field;

    #[cfg(windows)]
    #[test]
    fn uninstall_stdio_is_configured() {
        // The uninstall branch nulls stdio to survive invalid inherited handles
        // when Inno Setup launches the helper with SW_HIDE.  This test proves
        // the configurator can be applied to a Command without panicking.
        use std::process::Command;
        let mut cmd = Command::new("cmd");
        super::configure_uninstall_stdio(&mut cmd);
    }

    #[test]
    fn unescapes_spaces_backslashes_and_quotes() {
        let text = r#"{"data_dir": "C:\\Users\\Alice Liddell\\LAMF\\data\"quoted"}"#;
        assert_eq!(
            json_string_field(text, "data_dir"),
            Some(r#"C:\Users\Alice Liddell\LAMF\data"quoted"#.to_string())
        );
    }

    #[test]
    fn unescapes_unicode_omega() {
        let text = r#"{"data_dir": "C:\\tmp\\LAMF Install \u03a9\\Private Memory"}"#;
        assert_eq!(
            json_string_field(text, "data_dir"),
            Some("C:\\tmp\\LAMF Install Ω\\Private Memory".to_string())
        );
    }

    #[test]
    fn unescapes_non_bmp_surrogate_pair() {
        // U+1F600 GRINNING FACE = \uD83D\uDE00
        let text = r#"{"data_dir": "C:\\tmp\\LAMF \uD83D\uDE00\\data"}"#;
        assert_eq!(
            json_string_field(text, "data_dir"),
            Some("C:\\tmp\\LAMF 😀\\data".to_string())
        );
    }

    #[test]
    fn unescapes_standard_control_escapes() {
        let text = r#"{"data_dir": "line1\nline2\tcol\r"}"#;
        assert_eq!(
            json_string_field(text, "data_dir"),
            Some("line1\nline2\tcol\r".to_string())
        );
    }

    #[test]
    fn rejects_invalid_escape() {
        let text = r#"{"data_dir": "C:\\tmp\x"}"#;
        assert_eq!(json_string_field(text, "data_dir"), None);
    }

    #[test]
    fn rejects_lone_high_surrogate() {
        let text = r#"{"data_dir": "\uD83D"}"#;
        assert_eq!(json_string_field(text, "data_dir"), None);
    }

    #[test]
    fn leaves_unrelated_unicode_intact() {
        let text = r#"{"data_dir": "C:\\tmp\\Ω"}"#;
        assert_eq!(
            json_string_field(text, "data_dir"),
            Some("C:\\tmp\\Ω".to_string())
        );
    }
}
